# Generated by Django 5.2 on 2025-05-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.CharField(default='gfdr', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='gfdr', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='gfdr', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='gfdr', max_length=150),
        ),
    ]
