# Generated by Django 5.2 on 2025-04-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
